import type { FlavorCategory, ProductType } from '@prisma/client';

export const WOTOFO_CATALOG_SCHEMA_VERSION = '1.0';
export const WOTOFO_SOURCE_VERIFIED_AT = '2026-07-20T00:00:00.000Z';
export const WOTOFO_OFFICIAL_ORIGIN = 'https://www.wotofo.com';

export interface ReviewedFlavor {
  canonicalName: string;
  nameFr: string;
  nameAr: string;
  category: FlavorCategory;
}

export interface WotofoProductDefinition {
  key: string;
  handle: string;
  name: string;
  family: string;
  model: string;
  productType: ProductType;
  nicotineStrengthMg: number | null;
  puffCount: number | null;
  liquidCapacityMl: number | null;
  optionKind: 'flavor' | 'color';
  options: readonly string[];
}

const flavor = (
  canonicalName: string,
  nameFr: string,
  nameAr: string,
  category: FlavorCategory,
): ReviewedFlavor => ({ canonicalName, nameFr, nameAr, category });

/**
 * Human-reviewed catalogue labels. Brand and model names are intentionally not translated. The
 * canonical English value is the stable identity used by imports, filters and deterministic SKUs.
 */
export const WOTOFO_FLAVORS: Readonly<Record<string, ReviewedFlavor>> = Object.freeze({
  'Arabic Coffee': flavor('Arabic Coffee', 'Café arabe', 'قهوة عربية', 'DRINK'),
  'Black Ice': flavor('Black Ice', 'Glace noire', 'ثلج أسود', 'ICE'),
  'Blackberry Banana': flavor(
    'Blackberry Banana',
    'Mûre et banane',
    'توت أسود وموز',
    'MIXED_FRUIT',
  ),
  'Blackberry Ice': flavor('Blackberry Ice', 'Mûre glacée', 'توت أسود مثلج', 'ICE'),
  'Blackcurrant Ice': flavor('Blackcurrant Ice', 'Cassis glacé', 'كشمش أسود مثلج', 'ICE'),
  'Blue Razz Ice': flavor('Blue Razz Ice', 'Framboise bleue glacée', 'توت أزرق مثلج', 'ICE'),
  'Blue Razz Lemonade': flavor(
    'Blue Razz Lemonade',
    'Limonade à la framboise bleue',
    'ليموناضة بالتوت الأزرق',
    'DRINK',
  ),
  'Blueberry Ice': flavor('Blueberry Ice', 'Myrtille glacée', 'توت أزرق مثلج', 'ICE'),
  'Blueberry Pomegranate': flavor(
    'Blueberry Pomegranate',
    'Myrtille et grenade',
    'توت أزرق ورمان',
    'MIXED_FRUIT',
  ),
  'Blueberry Raspberry': flavor(
    'Blueberry Raspberry',
    'Myrtille et framboise',
    'توت أزرق وتوت العليق',
    'MIXED_FRUIT',
  ),
  'Blueberry Watermelon': flavor(
    'Blueberry Watermelon',
    'Myrtille et pastèque',
    'توت أزرق وبطيخ',
    'MIXED_FRUIT',
  ),
  'Caramel Tobacco': flavor('Caramel Tobacco', 'Tabac caramel', 'تبغ بالكراميل', 'TOBACCO'),
  'Cherry Cola': flavor('Cherry Cola', 'Cola cerise', 'كولا بالكرز', 'DRINK'),
  'Cherry Dragon Fruit': flavor(
    'Cherry Dragon Fruit',
    'Cerise et fruit du dragon',
    'كرز وفاكهة التنين',
    'MIXED_FRUIT',
  ),
  'Cherry Ice': flavor('Cherry Ice', 'Cerise glacée', 'كرز مثلج', 'ICE'),
  'Cherry Lemon': flavor('Cherry Lemon', 'Cerise et citron', 'كرز وليمون', 'MIXED_FRUIT'),
  Clear: flavor('Clear', 'Neutre', 'بدون نكهة', 'CLEAR'),
  'Coconut Dream': flavor('Coconut Dream', 'Rêve coco', 'حلم جوز الهند', 'DESSERT'),
  'Cola Ice': flavor('Cola Ice', 'Cola glacé', 'كولا مثلجة', 'DRINK'),
  'Cool Mint': flavor('Cool Mint', 'Menthe fraîche', 'نعناع بارد', 'MINT'),
  'Double Apple': flavor('Double Apple', 'Double pomme', 'تفاحتان', 'FRUIT'),
  'Dragon Fruit Berry': flavor(
    'Dragon Fruit Berry',
    'Fruit du dragon et baies',
    'فاكهة التنين والتوت',
    'MIXED_FRUIT',
  ),
  'Energy Drink': flavor('Energy Drink', 'Boisson énergisante', 'مشروب طاقة', 'DRINK'),
  English: flavor('English', 'English', 'إنجليش', 'OTHER'),
  'Forest Berries': flavor('Forest Berries', 'Fruits des bois', 'توت الغابة', 'MIXED_FRUIT'),
  'Grape Ice': flavor('Grape Ice', 'Raisin glacé', 'عنب مثلج', 'ICE'),
  'Guava Kiwi Passion Fruit': flavor(
    'Guava Kiwi Passion Fruit',
    'Goyave, kiwi et fruit de la passion',
    'جوافة وكيوي وفاكهة العاطفة',
    'MIXED_FRUIT',
  ),
  'Gum Mint': flavor('Gum Mint', 'Chewing-gum menthe', 'علكة بالنعناع', 'CANDY'),
  'Hawaiian Shore Ice': flavor(
    'Hawaiian Shore Ice',
    'Rivage hawaïen glacé',
    'شاطئ هاواي المثلج',
    'ICE',
  ),
  'Just Mint': flavor('Just Mint', 'Menthe pure', 'نعناع خالص', 'MINT'),
  'Lemon Mint': flavor('Lemon Mint', 'Citron menthe', 'ليمون ونعناع', 'MINT'),
  'Love 77': flavor('Love 77', 'Love 77', 'لوف 77', 'MIXED_FRUIT'),
  'Mango Dream': flavor('Mango Dream', 'Rêve mangue', 'حلم المانجو', 'DESSERT'),
  'Mango Ice': flavor('Mango Ice', 'Mangue glacée', 'مانجو مثلجة', 'ICE'),
  'Mango Passion Fruit': flavor(
    'Mango Passion Fruit',
    'Mangue et fruit de la passion',
    'مانجو وفاكهة العاطفة',
    'MIXED_FRUIT',
  ),
  'Melon Banana': flavor('Melon Banana', 'Melon et banane', 'شمام وموز', 'MIXED_FRUIT'),
  'Melon Blast': flavor('Melon Blast', 'Explosion de melon', 'انفجار الشمام', 'FRUIT'),
  'Melon Coconut': flavor('Melon Coconut', 'Melon et coco', 'شمام وجوز الهند', 'MIXED_FRUIT'),
  'Melon Kiwi Banana': flavor(
    'Melon Kiwi Banana',
    'Melon, kiwi et banane',
    'شمام وكيوي وموز',
    'MIXED_FRUIT',
  ),
  'Mentos Mint': flavor('Mentos Mint', 'Menthe Mentos', 'نعناع منتوس', 'CANDY'),
  Mint: flavor('Mint', 'Menthe', 'نعناع', 'MINT'),
  'Mixed Berries': flavor('Mixed Berries', 'Mélange de baies', 'مزيج التوت', 'MIXED_FRUIT'),
  'Mixed Grape': flavor('Mixed Grape', 'Mélange de raisins', 'مزيج العنب', 'MIXED_FRUIT'),
  'Monster Ice': flavor('Monster Ice', 'Monster glacé', 'مونستر مثلج', 'DRINK'),
  'Moscow Evenings': flavor('Moscow Evenings', 'Soirées de Moscou', 'أمسيات موسكو', 'DRINK'),
  'Passion Fruit Melon': flavor(
    'Passion Fruit Melon',
    'Fruit de la passion et melon',
    'فاكهة العاطفة والشمام',
    'MIXED_FRUIT',
  ),
  'Passionfruit Guava': flavor(
    'Passionfruit Guava',
    'Fruit de la passion et goyave',
    'فاكهة العاطفة والجوافة',
    'MIXED_FRUIT',
  ),
  'Peach Berries': flavor('Peach Berries', 'Pêche et baies', 'خوخ وتوت', 'MIXED_FRUIT'),
  'Peach Ice': flavor('Peach Ice', 'Pêche glacée', 'خوخ مثلج', 'ICE'),
  'Peach Mango Ice': flavor(
    'Peach Mango Ice',
    'Pêche et mangue glacées',
    'خوخ ومانجو مثلجان',
    'ICE',
  ),
  'Peach Mango Watermelon': flavor(
    'Peach Mango Watermelon',
    'Pêche, mangue et pastèque',
    'خوخ ومانجو وبطيخ',
    'MIXED_FRUIT',
  ),
  'Pina Colada': flavor('Pina Colada', 'Piña colada', 'بينا كولادا', 'DRINK'),
  'Pineapple Coconut': flavor(
    'Pineapple Coconut',
    'Ananas et coco',
    'أناناس وجوز الهند',
    'MIXED_FRUIT',
  ),
  'Pineapple Ice': flavor('Pineapple Ice', 'Ananas glacé', 'أناناس مثلج', 'ICE'),
  'Pineapple Papaya': flavor(
    'Pineapple Papaya',
    'Ananas et papaye',
    'أناناس وبابايا',
    'MIXED_FRUIT',
  ),
  'Pineapple Peach Mango': flavor(
    'Pineapple Peach Mango',
    'Ananas, pêche et mangue',
    'أناناس وخوخ ومانجو',
    'MIXED_FRUIT',
  ),
  'Pink Bomb': flavor('Pink Bomb', 'Bombe rose', 'القنبلة الوردية', 'CANDY'),
  'Pink Lemon': flavor('Pink Lemon', 'Citron rose', 'ليمون وردي', 'FRUIT'),
  'Pink Lemonade': flavor('Pink Lemonade', 'Limonade rose', 'ليموناضة وردية', 'DRINK'),
  'Pomegranate Ice': flavor('Pomegranate Ice', 'Grenade glacée', 'رمان مثلج', 'ICE'),
  'Pomegranate Kiwi': flavor('Pomegranate Kiwi', 'Grenade et kiwi', 'رمان وكيوي', 'MIXED_FRUIT'),
  'Purple Razz Ice': flavor(
    'Purple Razz Ice',
    'Framboise violette glacée',
    'توت بنفسجي مثلج',
    'ICE',
  ),
  Skittlez: flavor('Skittlez', 'Skittlez', 'سكيتلز', 'CANDY'),
  'Sour Apple': flavor('Sour Apple', 'Pomme acidulée', 'تفاح حامض', 'CANDY'),
  Spearmint: flavor('Spearmint', 'Menthe verte', 'نعناع أخضر', 'MINT'),
  'Strawberry Banana': flavor(
    'Strawberry Banana',
    'Fraise et banane',
    'فراولة وموز',
    'MIXED_FRUIT',
  ),
  'Strawberry Cone': flavor('Strawberry Cone', 'Cornet fraise', 'قمع الفراولة', 'DESSERT'),
  'Strawberry Dragon Fruit': flavor(
    'Strawberry Dragon Fruit',
    'Fraise et fruit du dragon',
    'فراولة وفاكهة التنين',
    'MIXED_FRUIT',
  ),
  'Strawberry Ice': flavor('Strawberry Ice', 'Fraise glacée', 'فراولة مثلجة', 'ICE'),
  'Strawberry Kiwi': flavor('Strawberry Kiwi', 'Fraise et kiwi', 'فراولة وكيوي', 'MIXED_FRUIT'),
  'Strawberry Lush': flavor('Strawberry Lush', 'Fraise gourmande', 'فراولة غنية', 'FRUIT'),
  'Strawberry Mango': flavor(
    'Strawberry Mango',
    'Fraise et mangue',
    'فراولة ومانجو',
    'MIXED_FRUIT',
  ),
  'Strawberry Pina Colada': flavor(
    'Strawberry Pina Colada',
    'Piña colada fraise',
    'بينا كولادا بالفراولة',
    'DRINK',
  ),
  'Strawberry Raspberry Cherry': flavor(
    'Strawberry Raspberry Cherry',
    'Fraise, framboise et cerise',
    'فراولة وتوت العليق وكرز',
    'MIXED_FRUIT',
  ),
  'Strawberry Watermelon Ice': flavor(
    'Strawberry Watermelon Ice',
    'Fraise et pastèque glacées',
    'فراولة وبطيخ مثلجان',
    'ICE',
  ),
  'Three Melons': flavor('Three Melons', 'Trois melons', 'ثلاثة أنواع من الشمام', 'MIXED_FRUIT'),
  Tobacco: flavor('Tobacco', 'Tabac', 'تبغ', 'TOBACCO'),
  'Triple Berry': flavor('Triple Berry', 'Triple baie', 'ثلاثة أنواع من التوت', 'MIXED_FRUIT'),
  'Tropical Ice': flavor('Tropical Ice', 'Tropical glacé', 'استوائي مثلج', 'ICE'),
  'Watermelon Bubblegum': flavor(
    'Watermelon Bubblegum',
    'Chewing-gum pastèque',
    'علكة البطيخ',
    'CANDY',
  ),
  'Watermelon Dragon Fruit': flavor(
    'Watermelon Dragon Fruit',
    'Pastèque et fruit du dragon',
    'بطيخ وفاكهة التنين',
    'MIXED_FRUIT',
  ),
  'Watermelon Ice': flavor('Watermelon Ice', 'Pastèque glacée', 'بطيخ مثلج', 'ICE'),
});

const NEXBAR_30K_20 = [
  'Cherry Dragon Fruit',
  'Forest Berries',
  'Guava Kiwi Passion Fruit',
  'Just Mint',
  'Love 77',
  'Mango Ice',
  'Melon Kiwi Banana',
  'Mixed Berries',
  'Monster Ice',
  'Moscow Evenings',
  'Peach Ice',
  'Peach Mango Watermelon',
  'Pineapple Ice',
  'Pomegranate Ice',
  'Strawberry Banana',
  'Strawberry Ice',
  'Strawberry Kiwi',
  'Strawberry Watermelon Ice',
  'Three Melons',
  'Watermelon Ice',
] as const;

const NEXBAR_25K_20 = [
  'Watermelon Ice',
  'Melon Kiwi Banana',
  'Strawberry Ice',
  'Coconut Dream',
  'Strawberry Dragon Fruit',
  'Triple Berry',
  'Pineapple Papaya',
  'Mango Dream',
  'Just Mint',
  'Peach Ice',
  'Passionfruit Guava',
  'Pink Bomb',
  'Pomegranate Kiwi',
  'Blueberry Raspberry',
  'Peach Mango Watermelon',
  'Moscow Evenings',
  'Strawberry Kiwi',
  'Love 77',
  'Blueberry Watermelon',
  'Monster Ice',
] as const;

const NEXBAR_18K_VIVID_20 = [
  'Watermelon Bubblegum',
  'Cherry Ice',
  'Peach Mango Ice',
  'Melon Blast',
  'Pineapple Ice',
  'Melon Kiwi Banana',
  'Guava Kiwi Passion Fruit',
  'Lemon Mint',
  'Blueberry Ice',
  'Forest Berries',
  'Strawberry Ice',
  'Watermelon Ice',
  'Love 77',
  'Mango Ice',
  'Moscow Evenings',
  'Mango Passion Fruit',
  'Blueberry Pomegranate',
  'Strawberry Pina Colada',
  'Mixed Grape',
  'Melon Coconut',
] as const;

const NEXBAR_18K_20 = [
  'Cherry Ice',
  'Forest Berries',
  'Guava Kiwi Passion Fruit',
  'Hawaiian Shore Ice',
  'Mango Ice',
  'Melon Kiwi Banana',
  'Mixed Berries',
  'Peach Ice',
  'Peach Mango Watermelon',
  'Pomegranate Ice',
  'Strawberry Banana',
  'Strawberry Ice',
  'Strawberry Kiwi',
  'Three Melons',
  'Watermelon Ice',
] as const;

const NEXBAR_18K_50 = [
  'Blackberry Ice',
  'Cherry Dragon Fruit',
  'Forest Berries',
  'Guava Kiwi Passion Fruit',
  'Hawaiian Shore Ice',
  'Mango Ice',
  'Melon Blast',
  'Melon Kiwi Banana',
  'Peach Mango Watermelon',
  'Pineapple Ice',
  'Pomegranate Ice',
  'Strawberry Ice',
  'Strawberry Kiwi',
  'Watermelon Dragon Fruit',
  'Watermelon Ice',
] as const;

const NEXBAR_20K_20 = [
  'Tropical Ice',
  'Three Melons',
  'Blueberry Raspberry',
  'Pina Colada',
  'Blue Razz Ice',
  'Hawaiian Shore Ice',
  'Dragon Fruit Berry',
  'Strawberry Kiwi',
  'Blackberry Ice',
  'Watermelon Ice',
] as const;

const NEXBAR_16K = [
  'Mint',
  'Mentos Mint',
  'Skittlez',
  'Grape Ice',
  'Strawberry Kiwi',
  'Watermelon Bubblegum',
  'Blackberry Ice',
  'Sour Apple',
  'Clear',
  'Blueberry Raspberry',
  'Strawberry Ice',
  'Cherry Lemon',
  'Monster Ice',
  'Spearmint',
  'Watermelon Ice',
] as const;

const NEXPOD_15K_POD_20 = [
  ...NEXBAR_30K_20,
  'Arabic Coffee',
  'Cherry Cola',
  'English',
  'Grape Ice',
  'Gum Mint',
  'Lemon Mint',
  'Pineapple Coconut',
  'Pink Lemonade',
  'Strawberry Raspberry Cherry',
  'Tobacco',
] as const;

const NEXPOD_15K_POD_50 = [
  'Black Ice',
  'Blackcurrant Ice',
  'Cool Mint',
  'Energy Drink',
  'Forest Berries',
  'Grape Ice',
  'Guava Kiwi Passion Fruit',
  'Hawaiian Shore Ice',
  'Lemon Mint',
  'Mango Ice',
  'Peach Mango Watermelon',
  'Pina Colada',
  'Pineapple Ice',
  'Strawberry Ice',
  'Watermelon Ice',
] as const;

const NEXPOD_REPLACEMENT_20 = [
  'Blackberry Ice',
  'Blue Razz Lemonade',
  'Blueberry Ice',
  'Caramel Tobacco',
  'Cherry Dragon Fruit',
  'Cherry Ice',
  'Cola Ice',
  'Double Apple',
  'Dragon Fruit Berry',
  'Forest Berries',
  'Grape Ice',
  'Hawaiian Shore Ice',
  'Lemon Mint',
  'Mango Ice',
  'Melon Kiwi Banana',
  'Mint',
  'Mixed Berries',
  'Monster Ice',
  'Peach Berries',
  'Peach Ice',
  'Peach Mango Ice',
  'Peach Mango Watermelon',
  'Pina Colada',
  'Pomegranate Ice',
  'Purple Razz Ice',
  'Strawberry Banana',
  'Strawberry Ice',
  'Strawberry Mango',
  'Three Melons',
  'Tropical Ice',
  'Watermelon Ice',
  'Blackberry Banana',
  'Blueberry Watermelon',
  'Love 77',
  'Mango Passion Fruit',
  'Melon Banana',
  'Mixed Grape',
  'Moscow Evenings',
  'Passion Fruit Melon',
  'Pineapple Peach Mango',
  'Pink Lemon',
  'Strawberry Cone',
  'Strawberry Pina Colada',
  'Strawberry Raspberry Cherry',
  'Strawberry Watermelon Ice',
] as const;

const NEXPOD_REPLACEMENT_50 = [
  'Blue Razz Lemonade',
  'Cherry Dragon Fruit',
  'Cola Ice',
  'Double Apple',
  'Forest Berries',
  'Grape Ice',
  'Hawaiian Shore Ice',
  'Lemon Mint',
  'Mango Ice',
  'Melon Kiwi Banana',
  'Mint',
  'Mixed Berries',
  'Monster Ice',
  'Peach Ice',
  'Peach Mango Ice',
  'Peach Mango Watermelon',
  'Pina Colada',
  'Pineapple Ice',
  'Pomegranate Ice',
  'Strawberry Ice',
  'Strawberry Kiwi',
  'Strawberry Lush',
  'Three Melons',
  'Tropical Ice',
  'Watermelon Ice',
  'Caramel Tobacco',
] as const;

const NEXPOD_KIT_20 = [
  'Mango Ice',
  'Melon Blast',
  'Mint',
  'Mixed Berries',
  'Monster Ice',
  'Peach Mango Watermelon',
  'Pineapple Ice',
  'Strawberry Banana',
  'Tropical Ice',
  'Watermelon Ice',
] as const;

const NEXPOD_KIT_50 = [
  'Double Apple',
  'Forest Berries',
  'Hawaiian Shore Ice',
  'Lemon Mint',
  'Mango Ice',
  'Monster Ice',
  'Strawberry Kiwi',
  'Three Melons',
  'Tropical Ice',
  'Watermelon Ice',
] as const;

const product = (definition: WotofoProductDefinition): WotofoProductDefinition => definition;

/** Official Wotofo options verified from the product JSON endpoints on 2026-07-20. */
export const WOTOFO_PRODUCTS: readonly WotofoProductDefinition[] = Object.freeze([
  product({
    key: 'nexbar-30k-20',
    handle: 'nexbar-30k',
    name: 'Wotofo nexBAR 30K',
    family: 'nexBAR',
    model: '30K',
    productType: 'DISPOSABLE',
    nicotineStrengthMg: 20,
    puffCount: 30_000,
    liquidCapacityMl: 35,
    optionKind: 'flavor',
    options: NEXBAR_30K_20,
  }),
  product({
    key: 'nexbar-25k-20',
    handle: 'nexbar-25k-20mg',
    name: 'Wotofo nexBAR 25K',
    family: 'nexBAR',
    model: '25K',
    productType: 'DISPOSABLE',
    nicotineStrengthMg: 20,
    puffCount: 25_000,
    liquidCapacityMl: 25,
    optionKind: 'flavor',
    options: NEXBAR_25K_20,
  }),
  product({
    key: 'nexbar-18k-vivid-20',
    handle: 'wotofo-nexbar-18k-vivid-edition',
    name: 'Wotofo nexBAR 18K Vivid Edition',
    family: 'nexBAR',
    model: '18K Vivid Edition',
    productType: 'DISPOSABLE',
    nicotineStrengthMg: 20,
    puffCount: 18_000,
    liquidCapacityMl: 21,
    optionKind: 'flavor',
    options: NEXBAR_18K_VIVID_20,
  }),
  product({
    key: 'nexbar-18k-20',
    handle: 'wotofo-nexbar-18k',
    name: 'Wotofo nexBAR 18K',
    family: 'nexBAR',
    model: '18K',
    productType: 'DISPOSABLE',
    nicotineStrengthMg: 20,
    puffCount: 18_000,
    liquidCapacityMl: 21,
    optionKind: 'flavor',
    options: NEXBAR_18K_20,
  }),
  product({
    key: 'nexbar-18k-50',
    handle: 'wotofo-nexbar-18k-50mg',
    name: 'Wotofo nexBAR 18K 50mg',
    family: 'nexBAR',
    model: '18K',
    productType: 'DISPOSABLE',
    nicotineStrengthMg: 50,
    puffCount: 18_000,
    liquidCapacityMl: 21,
    optionKind: 'flavor',
    options: NEXBAR_18K_50,
  }),
  product({
    key: 'nexbar-20k-20',
    handle: 'wotofo-nexbar-20k',
    name: 'Wotofo nexBAR 20K',
    family: 'nexBAR',
    model: '20K',
    productType: 'DISPOSABLE',
    nicotineStrengthMg: 20,
    puffCount: 20_000,
    liquidCapacityMl: 24,
    optionKind: 'flavor',
    options: NEXBAR_20K_20,
  }),
  product({
    key: 'nexbar-16k-20',
    handle: 'wotofo-nexbar-16k',
    name: 'Wotofo nexBAR 16K 20mg',
    family: 'nexBAR',
    model: '16K',
    productType: 'DISPOSABLE',
    nicotineStrengthMg: 20,
    puffCount: 16_000,
    liquidCapacityMl: 20,
    optionKind: 'flavor',
    options: NEXBAR_16K,
  }),
  product({
    key: 'nexbar-16k-50',
    handle: 'wotofo-nexbar-16k',
    name: 'Wotofo nexBAR 16K 50mg',
    family: 'nexBAR',
    model: '16K',
    productType: 'DISPOSABLE',
    nicotineStrengthMg: 50,
    puffCount: 16_000,
    liquidCapacityMl: 20,
    optionKind: 'flavor',
    options: NEXBAR_16K,
  }),
  product({
    key: 'nexbar-10k-20',
    handle: 'wotofo-nexbar-10k',
    name: 'Wotofo nexBAR 10K',
    family: 'nexBAR',
    model: '10K',
    productType: 'DISPOSABLE',
    nicotineStrengthMg: 20,
    puffCount: 10_000,
    liquidCapacityMl: 20,
    optionKind: 'flavor',
    options: NEXBAR_30K_20,
  }),
  product({
    key: 'nexpod-15k-kit-20',
    handle: 'nexpod-15k-kit-20mg',
    name: 'Wotofo nexPOD 15K Kit',
    family: 'nexPOD',
    model: '15K Kit',
    productType: 'PREFILLED_POD_KIT',
    nicotineStrengthMg: 20,
    puffCount: 15_000,
    liquidCapacityMl: 18,
    optionKind: 'flavor',
    options: NEXBAR_30K_20,
  }),
  product({
    key: 'nexpod-15k-pod-20',
    handle: 'nexpod-15k-prefilled-pod-20mg',
    name: 'Wotofo nexPOD 15K Prefilled Pod',
    family: 'nexPOD',
    model: '15K Prefilled Pod',
    productType: 'PREFILLED_REPLACEMENT_POD',
    nicotineStrengthMg: 20,
    puffCount: 15_000,
    liquidCapacityMl: 18,
    optionKind: 'flavor',
    options: NEXPOD_15K_POD_20,
  }),
  product({
    key: 'nexpod-15k-pod-50',
    handle: 'nexpod-15k-prefilled-pod-50mg',
    name: 'Wotofo nexPOD 15K Prefilled Pod 50mg',
    family: 'nexPOD',
    model: '15K Prefilled Pod',
    productType: 'PREFILLED_REPLACEMENT_POD',
    nicotineStrengthMg: 50,
    puffCount: 15_000,
    liquidCapacityMl: 18,
    optionKind: 'flavor',
    options: NEXPOD_15K_POD_50,
  }),
  product({
    key: 'nexpod-15k-device',
    handle: 'nexpod-15k-device',
    name: 'Wotofo nexPOD 15K Device',
    family: 'nexPOD',
    model: '15K Device',
    productType: 'DEVICE',
    nicotineStrengthMg: null,
    puffCount: null,
    liquidCapacityMl: null,
    optionKind: 'color',
    options: ['Fiery Sunrise', 'Blue Gradient', 'Rose Gold', 'Red', 'Black'],
  }),
  product({
    key: 'nexpod-15k-pro-device',
    handle: 'nexpod-15k-pro-device',
    name: 'Wotofo nexPOD 15K Pro Device',
    family: 'nexPOD',
    model: '15K Pro Device',
    productType: 'DEVICE',
    nicotineStrengthMg: null,
    puffCount: null,
    liquidCapacityMl: null,
    optionKind: 'color',
    options: ['Black', 'Blue', 'Cosmic Orange', 'Red', 'Rose Gold', 'Silver'],
  }),
  product({
    key: 'nexpod-5k-pod-20',
    handle: 'nexpod-replacement-pod-20mg',
    name: 'Wotofo nexPOD Replacement Pod 20mg',
    family: 'nexPOD',
    model: '5K Replacement Pod',
    productType: 'PREFILLED_REPLACEMENT_POD',
    nicotineStrengthMg: 20,
    puffCount: 5_000,
    liquidCapacityMl: 10,
    optionKind: 'flavor',
    options: NEXPOD_REPLACEMENT_20,
  }),
  product({
    key: 'nexpod-5k-pod-50',
    handle: 'nexpod-replacement-pod',
    name: 'Wotofo nexPOD Replacement Pod 50mg',
    family: 'nexPOD',
    model: '5K Replacement Pod',
    productType: 'PREFILLED_REPLACEMENT_POD',
    nicotineStrengthMg: 50,
    puffCount: 5_000,
    liquidCapacityMl: 10,
    optionKind: 'flavor',
    options: NEXPOD_REPLACEMENT_50,
  }),
  product({
    key: 'nexpod-kit-20',
    handle: 'nexpod-kit-20mg',
    name: 'Wotofo nexPOD Kit 20mg',
    family: 'nexPOD',
    model: '5K Kit',
    productType: 'PREFILLED_POD_KIT',
    nicotineStrengthMg: 20,
    puffCount: 5_000,
    liquidCapacityMl: 10,
    optionKind: 'flavor',
    options: NEXPOD_KIT_20,
  }),
  product({
    key: 'nexpod-kit-50',
    handle: 'nexpod-kit',
    name: 'Wotofo nexPOD Kit 50mg',
    family: 'nexPOD',
    model: '5K Kit',
    productType: 'PREFILLED_POD_KIT',
    nicotineStrengthMg: 50,
    puffCount: 5_000,
    liquidCapacityMl: 10,
    optionKind: 'flavor',
    options: NEXPOD_KIT_50,
  }),
  product({
    key: 'aerok-pod-kit',
    handle: 'aerok-pod-kit',
    name: 'Wotofo AEROK Pod Kit',
    family: 'AEROK',
    model: 'Pod Kit',
    productType: 'POD',
    nicotineStrengthMg: null,
    puffCount: null,
    liquidCapacityMl: 4,
    optionKind: 'color',
    options: ['Silver', 'Blue', 'Black', 'Burgundy Red'],
  }),
]);

export const WOTOFO_EXPECTED_PRODUCT_COUNT = WOTOFO_PRODUCTS.length;
export const WOTOFO_EXPECTED_VARIANT_COUNT = WOTOFO_PRODUCTS.reduce(
  (total, definition) => total + definition.options.length,
  0,
);

export const officialProductUrl = (handle: string): string =>
  `${WOTOFO_OFFICIAL_ORIGIN}/products/${handle}`;

export const officialProductJsonUrl = (handle: string): string =>
  `${officialProductUrl(handle)}.js`;

export const reviewedFlavor = (canonicalName: string): ReviewedFlavor => {
  const reviewed = WOTOFO_FLAVORS[canonicalName];
  if (!reviewed) throw new Error(`Missing reviewed Wotofo flavor translation: ${canonicalName}`);
  return reviewed;
};
