import { randomBytes } from 'node:crypto';

const PREFIX_PATTERN = /^[A-Za-z][A-Za-z0-9_]{0,39}$/;
const GENERATED_NAME_PATTERN = /^[A-Za-z][A-Za-z0-9_]{0,39}_\d{14}_[a-f0-9]{8}$/;
const GENERATED_USER_PATTERN = /^vape_drill_[a-f0-9]{8}$/;

export const parseRestoreDrillArguments = (arguments_) => {
  if (arguments_.length === 1 && ['--help', '-h'].includes(arguments_[0])) {
    return { help: true, backupPath: null, keepDatabase: false };
  }
  if (arguments_.length < 1 || arguments_.length > 2) {
    throw new Error('Restore drill arguments are invalid');
  }
  const [backupPath, option] = arguments_;
  if (!backupPath || (option && option !== '--keep-isolated-database')) {
    throw new Error('Restore drill arguments are invalid');
  }
  return { help: false, backupPath, keepDatabase: option === '--keep-isolated-database' };
};

export const createDrillDatabaseName = (
  prefix = 'vape_restore_drill',
  now = new Date(),
  nonce = randomBytes(4).toString('hex'),
) => {
  if (!PREFIX_PATTERN.test(prefix)) throw new Error('RESTORE_DRILL_DATABASE_PREFIX is invalid');
  if (!/^[a-f0-9]{8}$/.test(nonce)) throw new Error('Restore drill nonce is invalid');
  const timestamp = now
    .toISOString()
    .replaceAll(/[-:TZ.]/g, '')
    .slice(0, 14);
  const databaseName = `${prefix}_${timestamp}_${nonce}`;
  if (!GENERATED_NAME_PATTERN.test(databaseName) || databaseName.length > 64) {
    throw new Error('Generated restore drill database name is invalid');
  }
  return databaseName;
};

export const assertGeneratedDrillDatabaseName = (databaseName) => {
  if (!GENERATED_NAME_PATTERN.test(databaseName) || databaseName.length > 64) {
    throw new Error('Refusing to mutate a database that was not generated by the restore drill');
  }
};

export const createDrillUserName = (nonce = randomBytes(4).toString('hex')) => {
  const userName = `vape_drill_${nonce}`;
  if (!GENERATED_USER_PATTERN.test(userName)) throw new Error('Restore drill user name is invalid');
  return userName;
};

export const assertGeneratedDrillUserName = (userName) => {
  if (!GENERATED_USER_PATTERN.test(userName)) {
    throw new Error('Refusing to mutate a user that was not generated by the restore drill');
  }
};

export const assertIsolatedDrillTarget = ({ isolated, confirmedHost, actualHost }) => {
  if (isolated !== 'true' || !confirmedHost || confirmedHost !== actualHost) {
    throw new Error('Restore drill isolated-target confirmation does not match');
  }
};

export const databaseUrlForName = (adminUrl, databaseName) => {
  assertGeneratedDrillDatabaseName(databaseName);
  if (!URL.canParse(adminUrl)) {
    throw new Error('RESTORE_DRILL_ADMIN_URL must be a complete MySQL URL');
  }
  const parsed = new URL(adminUrl);
  if (parsed.protocol !== 'mysql:' || !parsed.hostname || !parsed.username) {
    throw new Error('RESTORE_DRILL_ADMIN_URL must be a complete MySQL URL');
  }
  parsed.pathname = `/${databaseName}`;
  return parsed.toString();
};

export const restoreDrillUsage = `Usage: pnpm restore:drill <backup.sql.gz[.enc]> [--keep-isolated-database]

Creates a randomly named database on RESTORE_DRILL_ADMIN_URL, restores and verifies the backup,
writes a drill report, and drops the database by default. Keeping it requires both the command-line
flag and RESTORE_DRILL_KEEP_DATABASE=true.`;
