-- CreateTable
CREATE TABLE `OutboxEvent` (
    `id` VARCHAR(30) NOT NULL,
    `deterministicKey` VARCHAR(191) NOT NULL,
    `aggregateType` VARCHAR(80) NOT NULL,
    `aggregateId` VARCHAR(80) NOT NULL,
    `eventType` VARCHAR(120) NOT NULL,
    `eventVersion` INTEGER NOT NULL DEFAULT 1,
    `payload` JSON NOT NULL,
    `status` ENUM('PENDING', 'LEASED', 'PUBLISHED', 'PROCESSING', 'RETRY', 'PROCESSED', 'DEAD_LETTER', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
    `availableAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `leaseOwner` VARCHAR(160) NULL,
    `leaseExpiresAt` DATETIME(3) NULL,
    `attemptCount` INTEGER NOT NULL DEFAULT 0,
    `maxAttempts` INTEGER NOT NULL DEFAULT 8,
    `lastAttemptAt` DATETIME(3) NULL,
    `publishedAt` DATETIME(3) NULL,
    `publishedJobId` VARCHAR(191) NULL,
    `processedAt` DATETIME(3) NULL,
    `deadLetteredAt` DATETIME(3) NULL,
    `safeErrorCode` VARCHAR(100) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `OutboxEvent_deterministicKey_key`(`deterministicKey`),
    INDEX `OutboxEvent_status_availableAt_id_idx`(`status`, `availableAt`, `id`),
    INDEX `OutboxEvent_status_leaseExpiresAt_idx`(`status`, `leaseExpiresAt`),
    INDEX `OutboxEvent_aggregateType_aggregateId_createdAt_idx`(`aggregateType`, `aggregateId`, `createdAt`),
    INDEX `OutboxEvent_eventType_createdAt_idx`(`eventType`, `createdAt`),
    CONSTRAINT `OutboxEvent_eventVersion_positive` CHECK (`eventVersion` > 0),
    CONSTRAINT `OutboxEvent_attemptCount_nonnegative` CHECK (`attemptCount` >= 0),
    CONSTRAINT `OutboxEvent_maxAttempts_positive` CHECK (`maxAttempts` > 0),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
